{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2020-1976",
		"assignerOrgId": "d6c1279f-00f6-4ef7-9217-f89ffe703ec0",
		"assignerShortName": "palo_alto",
		"state": "PUBLISHED",
		"datePublished": "2020-02-12T17:00:00.000Z",
		"dateReserved": "2020-02-12T17:00:00.000Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "d6c1279f-00f6-4ef7-9217-f89ffe703ec0",
				"shortName": "palo_alto",
				"dateUpdated": "2020-02-12T22:57:08"
			},
			"title": "GlobalProtect App: Local denial-of-service (DoS) vulnerability on MacOS",
			"descriptions": [
				{
					"lang": "en",
					"value": "A denial-of-service (DoS) vulnerability in Palo Alto Networks GlobalProtect App running on Mac OS allows authenticated local users to cause the Mac OS kernel to hang or crash.\nThis issue affects GlobalProtect App 5.0.5 and earlier versions of GlobalProtect App 5.0 on Mac OS.\n",
					"supportingMedia": [
						{
							"base64": "false",
							"type": "text/html",
							"value": "<pre>A denial-of-service (DoS) vulnerability in Palo Alto Networks GlobalProtect App running on Mac OS allows authenticated local users to cause the Mac OS kernel to hang or crash.\nThis issue affects GlobalProtect App 5.0.5 and earlier versions of GlobalProtect App 5.0 on Mac OS.\n</pre>"
						}
					]
				}
			],
			"affected": [
				{
					"vendor": "Palo Alto Networks",
					"product": "GlobalProtect App",
					"platforms": [
						"Mac OS"
					],
					"versions": [
						{
							"status": "affected",
							"versionType": "custom",
							"version": "5.0",
							"lessThanOrEqual": "5.0.5",
							"changes": [
								{
									"at": "5.0.6",
									"status": "unaffected"
								}
							]
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-642 External Control of Critical State Data",
							"cweId": "CWE-642"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
						"attackVector": "LOCAL",
						"attackComplexity": "HIGH",
						"privilegesRequired": "LOW",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"availabilityImpact": "HIGH",
						"baseScore": 4.7,
						"baseSeverity": "MEDIUM"
					}
				}
			],
			"workarounds": [
				{
					"lang": "en",
					"value": "n/a",
					"supportingMedia": {
						"base64": false,
						"type": "text/html",
						"value": "n/a"
					}
				}
			],
			"solutions": [
				{
					"lang": "en",
					"value": "This issue is fixed in GlobalProtect App 5.0.6, GlobalProtect App 5.1.0, and all later versions.\n",
					"supportingMedia": {
						"base64": false,
						"type": "text/html",
						"value": "This issue is fixed in GlobalProtect App 5.0.6, GlobalProtect App 5.1.0, and all later versions.\n"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://security.paloaltonetworks.com/CVE-2020-1976"
				}
			],
			"credits": [
				{
					"lang": "en",
					"value": "This issue was discovered during a security test performed in collaboration with IOActive."
				}
			],
			"source": {
				"defect": [
					"GPC-9616"
				],
				"discovery": "INTERNAL"
			},
			"datePublic": "2020-02-12T17:00:00.000Z",
			"x_generator": {
				"engine": "Vulnogram 0.0.9"
			},
			"x_affectedList": [
				"GlobalProtect App 5.0.5",
				"GlobalProtect App 5.0.4",
				"GlobalProtect App 5.0.3",
				"GlobalProtect App 5.0.2",
				"GlobalProtect App 5.0.1",
				"GlobalProtect App 5.0.0",
				"GlobalProtect App 5.0"
			]
		}
	}
}
